spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.219.103:3306/nh80db?characterEncoding=UTF-8&serverTimezone=UTC
    username: sa
    password: izex_0329
    jpa:
      properties:
        hibernate:
          show_sql: true
          format_sql: true
server:
  port: 11044
