spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      jdbc-url: jdbc:mariadb://192.168.219.105:3306/nh80db?characterEncoding=UTF-8&serverTimezone=UTC
      username: sa
      password: izex_0329
      driver-class-name: org.mariadb.jdbc.Driver
      pool-name: hikari-cp
      maximum-pool-size: 100
      minimum-idle: 2
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testDB
#    h2:
#      console:
#        enabled: true
#        path: /h2-console
  graphql:
    graphiql:
      path: /graphiql
      enabled: true

server:
  port: 11040
